name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['stable', 'oldstable']
    env:
      GOLANGCI_LINT_VERSION: v2.5.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Run golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        uses: golangci/golangci-lint-action@v8
        with:
          args: --verbose
          version: ${{ env.GOLANGCI_LINT_VERSION }}

      - run: make test

      - run: make install
